from sqlalchemy import Column, Integer, String, Float, DateTime, Text, Boolean, JSON
from sqlalchemy.sql import func

from app.database import Base


class Signal(Base):
    """Trade signals generated by the scoring engine."""

    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticker = Column(String(10), nullable=False, index=True)
    direction = Column(String(4), nullable=False)  # "long" or "short"
    confidence = Column(Float, nullable=False)  # 0.0 – 1.0
    scanner_score = Column(Float, default=0.0)
    sentiment_score = Column(Float, default=0.0)
    technical_score = Column(Float, default=0.0)
    fundamental_score = Column(Float, default=0.0)
    composite_score = Column(Float, default=0.0)
    suggested_entry = Column(Float, nullable=True)
    suggested_stop = Column(Float, nullable=True)
    suggested_target = Column(Float, nullable=True)
    position_size_pct = Column(Float, nullable=True)
    status = Column(String(20), default="pending")  # pending, accepted, rejected, expired, executed
    metadata_json = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    expires_at = Column(DateTime(timezone=True), nullable=True)
    decision_reason = Column(Text, nullable=True)
