export default function HomePage() {
  return (
    <section className="max-w-4xl mx-auto px-4 py-24 text-center">
      <h1 className="text-5xl font-bold tracking-tight text-gray-900 mb-6">
        Amazon Affiliate Content,{' '}
        <span className="text-brand-600">Generated by AI</span>
      </h1>
      <p className="text-xl text-gray-600 mb-10 max-w-2xl mx-auto">
        Paste an Amazon product URL or ASIN, and get platform-optimized scripts,
        thumbnails, captions, and videos — with your affiliate ID baked in.
      </p>
      <div className="flex items-center justify-center gap-4">
        <a href="/signup" className="btn-primary text-lg px-8 py-3">
          Get Started Free
        </a>
        <a href="/demo" className="btn-secondary text-lg px-8 py-3">
          Watch Demo
        </a>
      </div>
    </section>
  );
}
